@startuml
title GC27 - Eriantys Sequence Diagram

actor User

box "Local"
participant View
participant Client
end box
box "Remote"
participant Connection
participant VirtualView
participant Controller
participant Model
end box

User -> View: Action
activate View

View -> Client: fireRequestEvent()
activate Client
Client -> Client: requestPerformed()
Client -> Client: send()

Client -> Connection: requestEvent()
activate Connection

Connection -> VirtualView: requestEvent()
activate VirtualView

VirtualView -> Controller: requestEvent()
activate Controller

Controller -> Model: requestEvent()
deactivate Controller
activate Model

Model --> VirtualView: AnswerEvent
destroy Model

VirtualView --> Connection: AnswerEvent
deactivate VirtualView

Connection --> Client: AnswerEvent
deactivate Connection

Client --> View: AnswerEvent
deactivate Client

View --> User: AnswerEvent
@enduml